### ISSUE TITLE
Throw android.os.FileUriExposedException on Android N when use Camera

### ISSUE THREAD

**Issue by JimChenCn** [fishwjy/MultiType-FilePicker#8]
Throw android.os.FileUriExposedException on Android N when use Camera

**Comment by fishwjy** [comment]
Fixed in version 1.0.1

**Comment by JiangShuLiang** [comment]
this problem is still on,I have update the version to 1.0.5 but when I click the video(try to play it while picking)or use camera,the app still crashed. the error info is :**FileUriExposedException**
